import { auth, db } from './firebase-config.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.7.1/firebase-auth.js';
import { collection, addDoc, getDocs, query, where, orderBy, onSnapshot, serverTimestamp, doc, setDoc, updateDoc, arrayUnion } from 'https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js';

const tabs=[...document.querySelectorAll('.chat-tab')], nav=[...document.querySelectorAll('.nav-btn[data-tab]')];
let user=null, currentRoom=null, currentContact=null, unsubscribe=null;
const localKey='gamechat-local';
const localData=()=>JSON.parse(localStorage.getItem(localKey)||'{"friends":[],"groups":[],"messages":{},"notifications":[]}');
const saveLocal=d=>localStorage.setItem(localKey,JSON.stringify(d));
function showTab(id){tabs.forEach(t=>t.classList.toggle('hidden',t.id!==id));nav.forEach(n=>n.classList.toggle('active',n.dataset.tab===id));if(id==='tab-friends')loadFriends();if(id==='tab-groups')loadGroups();if(id==='tab-notifications')loadNotifications()}
nav.forEach(n=>n.addEventListener('click',()=>showTab(n.dataset.tab)));
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.open)));
document.getElementById('clear-search').onclick=()=>{document.getElementById('user-search').value='';document.getElementById('search-results').innerHTML='Digite para pesquisar usuários cadastrados.'};
function initials(n){return (n||'?').trim().slice(0,2).toUpperCase()}
function item({name,email,kind='friend',id}){const el=document.createElement('div');el.className='card-item';el.innerHTML=`<div class="card-avatar">${initials(name)}</div><div class="card-info"><strong>${name}</strong><small>${email||kind}</small></div><button class="card-action">${kind==='group'?'Abrir':'Conversar'}</button>`;el.querySelector('button').onclick=()=>kind==='group'?openRoom(id,name,'grupo'):openRoom(id,name,email);return el}
async function loadFriends(){const box=document.getElementById('friends-list');box.innerHTML='';let d=localData();let friends=d.friends||[];try{if(user){const snap=await getDocs(query(collection(db,'amizades'),where('usuarios','array-contains',user.uid)));friends=snap.docs.map(x=>x.data()).flatMap(x=>x.membros||[]).filter(x=>x.email!==user.email)}}catch(e){}if(!friends.length){box.className='cards-list empty-state';box.textContent='Você ainda não tem conversas. Use a busca para encontrar usuários.';return}box.className='cards-list';friends.forEach(f=>box.appendChild(item({name:f.nome||f.email,email:f.email,id:f.uid||f.email})))}
let searchTimer;document.getElementById('user-search').addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>searchUsers(e.target.value.trim()),250)});
async function searchUsers(term){const box=document.getElementById('search-results');if(term.length<2){box.className='cards-list empty-state';box.textContent='Digite pelo menos 2 caracteres.';return}box.className='cards-list';box.innerHTML='<div class="empty-state">Buscando...</div>';let results=[];try{const snap=await getDocs(collection(db,'usuarios'));snap.forEach(x=>{const d=x.data();const email=(d.email||'').toLowerCase(),name=(d.nome||d.username||'').toLowerCase();if((email.includes(term.toLowerCase())||name.includes(term.toLowerCase()))&&email!==user?.email?.toLowerCase())results.push({uid:x.id,nome:d.nome||d.username||email,email})})}catch(e){const d=localData();results=(d.users||[]).filter(x=>(x.email+x.nome).toLowerCase().includes(term.toLowerCase()))}box.innerHTML='';if(!results.length){box.className='cards-list empty-state';box.textContent='Nenhum usuário encontrado.';return}results.forEach(u=>{const el=item({name:u.nome,email:u.email,id:u.uid});const btn=el.querySelector('button');btn.textContent='Convidar';btn.onclick=()=>sendInvite(u);box.appendChild(el)})}
async function sendInvite(u){try{if(user)await addDoc(collection(db,'convites'),{de:user.uid,deEmail:user.email,para:u.uid,paraEmail:u.email,nomeRemetente:user.email,status:'pendente',criadoEm:serverTimestamp()});const d=localData();d.notifications.push({text:`Convite de conversa enviado para ${u.email}`,type:'info'});saveLocal(d);alert('Convite enviado!')}catch(e){alert('Não foi possível enviar o convite agora.')}}
document.getElementById('create-group').onclick=async()=>{const name=prompt('Nome do grupo:');if(!name?.trim())return;const d=localData();const group={nome:name.trim(),criador:user?.uid||'local',membros:user?[{uid:user.uid,email:user.email}]:[],memberIds:user?[user.uid]:[]};try{const ref=await addDoc(collection(db,'grupos'),{...group,criadoEm:serverTimestamp()});group.id=ref.id}catch(e){group.id='local-'+Date.now()}d.groups.push(group);saveLocal(d);loadGroups();alert('Grupo criado com sucesso!')};
async function loadGroups(){const box=document.getElementById('groups-list');box.innerHTML='';let groups=localData().groups||[];try{if(user){const snap=await getDocs(query(collection(db,'grupos'),where('memberIds','array-contains',user.uid)));groups=[...groups,...snap.docs.map(x=>({id:x.id,...x.data(),nome:x.data().nome}))]}}catch(e){}groups=[...new Map(groups.map(g=>[g.id,g])).values()];if(!groups.length){box.className='cards-list empty-state';box.textContent='Nenhum grupo criado ainda.';return}box.className='cards-list';groups.forEach(g=>box.appendChild(item({name:g.nome,email:`${g.membros?.length||1} participante(s)`,kind:'group',id:g.id}))) }
async function loadNotifications(){const box=document.getElementById('notifications-list');box.innerHTML='';let list=localData().notifications||[];try{if(user){const snap=await getDocs(query(collection(db,'convites'),where('para','==',user.uid)));list=[...list,...snap.docs.map(x=>({id:x.id,text:`Convite de ${x.data().nomeRemetente||x.data().deEmail}`,invite:x.data()}))]}}catch(e){}if(!list.length){box.className='cards-list empty-state';box.textContent='Nenhuma notificação nova.';return}box.className='cards-list';list.forEach(n=>{const el=document.createElement('div');el.className='card-item';el.innerHTML=`<div class="card-avatar"><i class="fa-solid fa-envelope"></i></div><div class="card-info"><strong>${n.text}</strong><small>GameChat</small></div><button class="card-action">OK</button>`;el.querySelector('button').onclick=()=>el.remove();box.appendChild(el)})}
async function openRoom(id,name,email){currentContact={id,name,email};currentRoom=[user?.uid||'local',id].sort().join('_');document.getElementById('room-title').textContent=name;document.getElementById('room-subtitle').textContent=email||'grupo';document.getElementById('email-room').onclick=()=>emailMessage();showTab('tab-room');loadMessages()}
function renderMessages(list){const box=document.getElementById('messages-area');box.innerHTML='';if(!list.length){box.innerHTML='<div class="empty-state">Nenhuma mensagem ainda. Comece a conversa!</div>';return}list.forEach(m=>{const el=document.createElement('div');el.className='msg '+(m.uid===(user?.uid||'local')?'sent':'');el.innerHTML=`${m.text.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}<small>${m.email||''}</small>`;box.appendChild(el)});box.scrollTop=box.scrollHeight}
async function loadMessages(){if(unsubscribe)unsubscribe();let fallback=localData().messages?.[currentRoom]||[];renderMessages(fallback);try{const q=query(collection(db,'mensagens'),where('sala','==',currentRoom),orderBy('criadoEm'));unsubscribe=onSnapshot(q,s=>renderMessages(s.docs.map(x=>({id:x.id,...x.data()}))),()=>renderMessages(fallback))}catch(e){unsubscribe=null}}
document.getElementById('message-form').addEventListener('submit',async e=>{e.preventDefault();const input=document.getElementById('message-input'),text=input.value.trim();if(!text||!currentRoom)return;const m={sala:currentRoom,text,uid:user?.uid||'local',email:user?.email||'Você',criadoEm:Date.now()};try{await addDoc(collection(db,'mensagens'),{...m,criadoEm:serverTimestamp()})}catch(e){const d=localData();d.messages[currentRoom]=[...(d.messages[currentRoom]||[]),m];saveLocal(d);renderMessages(d.messages[currentRoom])}input.value=''});
function emailMessage(){const to=currentContact?.email;if(!to||to==='grupo'){alert('Este grupo não possui um único e-mail de destino.');return}location.href=`mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent('Mensagem pelo GameChat')}&body=${encodeURIComponent('Olá! Estou falando com você pelo GameChat.')}`}
document.getElementById('back-list').onclick=()=>showTab('tab-friends');
onAuthStateChanged(auth,u=>{user=u;showTab('tab-welcome')});
